name: Run Shell Script Example

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
        - name: Run multi-line shell script
          run: |
            echo "Starting script"
            pwd
            ls -l
            echo "Script finished"
